import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Sidbar from "../component/Sidbar"
const inter = Inter({ subsets: ['latin'] })
import Header from "../component/Header"
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className=''>
        <Header/>
        <div className="dashboard_conatiner">
          <Sidbar/>
          {children}
         </div>
      </body>
    </html>
  )
}
